linters:
  disable-all: true

  enable:
    - bodyclose
    - errcheck
    - errname
    - dupl
    - dupword
    - gofmt
    - cyclop
    - gosec
    - staticcheck
    - funlen
    - decorder
    - errorlint
    - gosimple
    - unused
    - testifylint
    - misspell
    - prealloc
    - ineffassign
    - nilerr
    - revive
    - tagalign
    - wsl
    - wrapcheck

linters-settings:
  cyclop:
    max-complexity: 10
  funlen:
    lines: 50
  dupl:
    threshold: 100
  gofmt:
    simplify: true
  staticcheck:
    checks: ["all"]

run:
  timeout: 5m

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
  sort-order:
    - linter
    - severity
    - file

severity:
  default-severity: warning
  case-sensitive: true
